services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: midatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest #comprobar ver.
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@mail.info
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8000:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
